let _adminTab = 'reservas';

const Admin = {
  open() { if (!Auth.isAdmin()) { UI.toast('Acceso denegado.', 'err'); return; } UI.showModal('modalAdmin'); this.showTab(_adminTab); },
  showTab(tab) { _adminTab = tab; const tabs = ['reservas', 'checklist', 'menu', 'usuarios']; document.querySelectorAll('.atab').forEach((btn, i) => btn.classList.toggle('active', tabs[i] === tab)); const content = document.getElementById('adminContent'); content.innerHTML = '<p class="loading-msg">⏳ Cargando...</p>'; const loaders = { reservas: () => this._loadReservas(), checklist: () => this._loadChecklist(), menu: () => this._loadMenuAdmin(), usuarios: () => this._loadUsuarios() }; loaders[tab]?.(); },
  async _loadReservas() { if (!FirebaseState.isReady()) { document.getElementById('adminContent').innerHTML = '<p class="empty-msg">Conecta Firebase.</p>'; return; } try { const { collection, getDocs, orderBy, query } = await import('https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js'); const q = query(collection(window.sakuraDB, 'reservaciones'), orderBy('fecha', 'desc')); const snap = await getDocs(q); const items = snap.docs.map(d => ({ id: d.id, ...d.data() })); this._renderReservasTable(items); } catch(e) { document.getElementById('adminContent').innerHTML = `<p class="empty-msg">Error: ${e.message}</p>`; } },
  _renderReservasTable(items) { if (!items.length) { document.getElementById('adminContent').innerHTML = '<p class="empty-msg">No hay reservaciones.</p>'; return; } const hoy = new Date().toISOString().split('T')[0]; document.getElementById('adminContent').innerHTML = `<div style="overflow-x:auto"><table class="adm-table"><thead><tr><th>Cliente</th><th>Fecha</th><th>Hora</th><th>Personas</th><th>Área</th><th>Estado</th><th>Notas</th><th>Acciones</th></tr></thead><tbody>${items.map(r => `<tr><td><strong>${r.nombre || '—'}</strong><br><small>${r.email || ''}</small></td><td>${r.fecha}</td><td>${r.horaEntrada} – ${r.horaSalida}</td><td style="text-align:center">${r.personas}</td><td>${r.area === 'fumar' ? '🚬 Fumar' : '🚭 No Fumar'}</td><td><span style="color:${r.estado === 'cancelada' ? '#e74c3c' : (r.fecha < hoy ? '#7f8c8d' : '#27ae60')}">${r.estado === 'cancelada' ? '✗ Cancelada' : (r.fecha < hoy ? '◉ Completada' : '✓ Confirmada')}</span></td><td style="max-width:10rem;">${r.notas || '—'}</td><td>${r.estado === 'confirmada' && r.fecha >= hoy ? `<button class="act-btn red" onclick="Admin.cancelarRes('${r.id}')">Cancelar</button>` : ''}</td></tr>`).join('')}</tbody></table></div>`; },
  async cancelarRes(id) { if (!confirm('¿Cancelar?')) return; try { const { doc, updateDoc } = await import('https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js'); await updateDoc(doc(window.sakuraDB, 'reservaciones', id), { estado: 'cancelada' }); UI.toast('Reservación cancelada.', 'info'); this._loadReservas(); } catch(e) { UI.toast('Error: ' + e.message, 'err'); } },
  async _loadMenuAdmin() { if (!FirebaseState.isReady()) { document.getElementById('adminContent').innerHTML = '<p class="empty-msg">Conecta Firebase.</p>'; return; } try { const { collection, getDocs } = await import('https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js'); const snap = await getDocs(collection(window.sakuraDB, 'menu')); const items = snap.docs.map(d => ({ id: d.id, ...d.data() })); document.getElementById('adminContent').innerHTML = `<div><table class="adm-table"><thead><tr><th>Platillo</th><th>Categoría</th><th>Precio</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${items.map(item => `<tr><td>${item.emoji} <strong>${item.name}</strong></td><td>${item.cat}</td><td>$${item.price}</td><td><span style="color:${item.disponible ? '#27ae60' : '#7f8c8d'}">${item.disponible ? '● Disponible' : '○ No disponible'}</span></td><td><button class="act-btn ${item.disponible ? 'red' : 'green'}" onclick="Admin.toggleItem('${item.id}', ${!item.disponible})">${item.disponible ? 'Desactivar' : 'Activar'}</button></td></tr>`).join('')}</tbody></table></div>`; } catch(e) { document.getElementById('adminContent').innerHTML = `<p class="empty-msg">Error: ${e.message}</p>`; } },
  async toggleItem(id, disponible) { try { const { doc, updateDoc } = await import('https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js'); await updateDoc(doc(window.sakuraDB, 'menu', id), { disponible }); UI.toast(`Platillo ${disponible ? 'activado' : 'desactivado'}.`, 'info'); this._loadMenuAdmin(); } catch(e) { UI.toast('Error: ' + e.message, 'err'); } },
  async _loadChecklist() { document.getElementById('adminContent').innerHTML = '<p class="loading-msg">📋 Check-in/out - Próximamente</p>'; },
  async _loadUsuarios() { if (!FirebaseState.isReady()) { document.getElementById('adminContent').innerHTML = '<p class="empty-msg">Conecta Firebase.</p>'; return; } try { const { collection, getDocs } = await import('https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js'); const snap = await getDocs(collection(window.sakuraDB, 'usuarios')); const users = snap.docs.map(d => ({ id: d.id, ...d.data() })); document.getElementById('adminContent').innerHTML = `<div><table class="adm-table"><thead><tr><th>Nombre</th><th>Correo</th><th>Teléfono</th><th>Rol</th><th>Acción</th></tr></thead><tbody>${users.map(u => `<tr><td><strong>${u.nombre || '—'}</strong></td><td>${u.email}</td><td>${u.telefono || '—'}</td><td><span style="background:${u.rol === 'admin' ? '#d9556b' : '#e8e0d5'}; color:${u.rol === 'admin' ? 'white' : '#7a6a5c'}; padding:.15em .6em; border-radius:20px;">${u.rol === 'admin' ? '⚙️ Admin' : '👤 User'}</span></td><td>${u.rol !== 'admin' ? `<button class="act-btn blue" onclick="Admin.makeAdmin('${u.id}')">Hacer Admin</button>` : `<button class="act-btn amber" onclick="Admin.removeAdmin('${u.id}')">Quitar Admin</button>`}</td></tr>`).join('')}</tbody></table></div>`; } catch(e) { document.getElementById('adminContent').innerHTML = `<p class="empty-msg">Error: ${e.message}</p>`; } },
  async makeAdmin(uid) { if (!confirm('¿Dar permisos de administrador?')) return; try { const { doc, updateDoc } = await import('https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js'); await updateDoc(doc(window.sakuraDB, 'usuarios', uid), { rol: 'admin' }); UI.toast('✅ Administrador asignado.', 'ok'); this._loadUsuarios(); } catch(e) { UI.toast('Error: ' + e.message, 'err'); } },
  async removeAdmin(uid) { if (!confirm('¿Quitar permisos?')) return; try { const { doc, updateDoc } = await import('https://www.gstatic.com/firebasejs/12.11.0/firebase-firestore.js'); await updateDoc(doc(window.sakuraDB, 'usuarios', uid), { rol: 'user' }); UI.toast('Permisos removidos.', 'info'); this._loadUsuarios(); } catch(e) { UI.toast('Error: ' + e.message, 'err'); } }
};
window.Admin = Admin;